version: "3.8"

# Service definitions
services:
  # ==============================================
  # PostgreSQL Database - Gitea Backend
  # ==============================================
  db:
    image: postgres:15
    container_name: gitea-db
    restart: unless-stopped
    
    # Environment configuration
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ:-Europe/Berlin}
    
    # Volume mounts for persistent data
    volumes:
      - gitea_db_data:/var/lib/postgresql/data
    
    # Network configuration
    networks:
      - gitea-internal

  # ==============================================
  # Gitea - Git Service
  # ==============================================
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    env_file:
      - ../.env
      - .env
    
    # Environment configuration
    environment:
      # Database Config
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      
      # Server Config
      - GITEA__server__DOMAIN=${SLD}.${TLD}
      - GITEA__server__SSH_DOMAIN=${SLD}.${TLD}
      - GITEA__server__ROOT_URL=https://${SLD}.${TLD}
      - GITEA__server__SSH_PORT=22
      - GITEA__server__HTTP_PORT=3000
      
      # Security Config
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN}
      
      # Admin Config
      - GITEA__security__INSTALL_LOCK=true
      
      # Timezone
      - TZ=${TZ:-Europe/Berlin}
    
    # Service dependencies
    depends_on:
      - db
    
    # Port exposure for SSH
    ports:
      - "2222:22"
    
    # Volume mounts for persistent data
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    
    # Traefik integration labels
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${SLD}.${TLD}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=myresolver"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    
    # Network configuration
    networks:
      - web
      - gitea-internal

# Named volumes for data persistence
volumes:
  gitea_data:
    external: true
    name: gitea_data
  gitea_db_data:
    external: true
    name: gitea_db_data

networks:
  web:
    external: true
    name: web
  gitea-internal:
    driver: bridge