version: "3.8"

services:
  traefik:
    container_name: traefik_proxy
    image: traefik:v2.10
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - traefik_data:/data
      - traefik_auth:/auth
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - sh
      - -c
      - |
        apk add --no-cache apache2-utils &&
        echo "${TRAEFIK_DASHBOARD_USER}:$$(htpasswd -nb ${TRAEFIK_DASHBOARD_USER} ${TRAEFIK_DASHBOARD_PASSWORD_CLEAR} | cut -d: -f2)" > /auth/.htpasswd &&
        exec traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_SUBDOMAIN:-traefik}.${TLD}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/auth/.htpasswd"
    networks:
      - web

# Named volumes for data persistence
volumes:
  traefik_data:
    external: true
    name: traefik_data
  traefik_auth:
    external: true
    name: traefik_auth

networks:
  web:
    external: true
    name: web