log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: web

certificatesResolvers:
  myresolver:
    acme:
      email: devnull@mailfence.com
      storage: /data/acme.json
      tlsChallenge: {}